In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets,linear_model
from sklearn.model_selection import train_test_split
#from sklearn.datasets import load_bosten

In [2]:
# load boston data using sklearn datasets
boston=datasets.load_boston()

# seprate data and target  
x=boston.data
y=boston.target
#print(x,y)

In [3]:
#tabular data structure with labeled axes (rows and columns)
df_x=pd.DataFrame(x,columns=boston.feature_names)
df_y=pd.DataFrame(y)
#print(df_x)
#print(df_y)

In [4]:
# create a model
reg=linear_model.LinearRegression()


In [5]:
#split data 
x_train,x_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.30,random_state=1)

In [6]:
#fit the model
reg.fit(x_train,y_train)

LinearRegression()

In [7]:
#Y=mx+c or Y=b0+b1x
# m and b1 is coefficient
reg.coef_


array([[-9.85424717e-02,  6.07841138e-02,  5.91715401e-02,
         2.43955988e+00, -2.14699650e+01,  2.79581385e+00,
         3.57459778e-03, -1.51627218e+00,  3.07541745e-01,
        -1.12800166e-02, -1.00546640e+00,  6.45018446e-03,
        -5.68834539e-01]])

In [8]:
# c and b0 is intercept
reg.intercept_

array([46.39649387])

In [9]:
# predict tne model
y_pred=reg.predict(x_test)

In [10]:
y_pred


array([[32.3914647 ],
       [27.94401279],
       [17.83762764],
       [21.66941388],
       [18.93639614],
       [20.01995795],
       [32.63414961],
       [17.86179976],
       [24.73211676],
       [26.77346826],
       [27.26138023],
       [28.63243014],
       [21.16103038],
       [27.15098589],
       [23.33198614],
       [21.02894005],
       [17.11819755],
       [37.52455938],
       [30.69864427],
       [ 8.46104486],
       [20.83966032],
       [16.26732451],
       [25.05030307],
       [24.8069032 ],
       [31.6789299 ],
       [10.98989363],
       [13.54111562],
       [16.54697099],
       [35.86699683],
       [14.69589266],
       [21.05655107],
       [13.90301353],
       [43.01321262],
       [17.80335305],
       [21.68817023],
       [20.45077825],
       [17.38095983],
       [26.81334904],
       [10.08706217],
       [19.96174586],
       [24.1983249 ],
       [21.00202622],
       [29.38682967],
       [16.33215467],
       [19.37439646],
       [14

In [11]:
y_test

0
307  28.2
343  23.9
47   16.6
67   22.0
362  20.8
..    ...
467  19.1
95   28.4
122  20.5
260  33.8
23   14.5

[152 rows x 1 columns]

In [12]:
# MSE(Mean Squared Error) using formula
np.mean((y_pred-y_test)**2)

0    19.831324
dtype: float64

In [13]:
# MSE using libreary
from sklearn.metrics import mean_squared_error

mean_squared_error(y_pred,y_test)

19.831323672062975